sudo: required

language: generic

services:
  - docker

env:
  global:
    - IMAGE_NAME="edevil/haypoll"
    - IMAGE_TAG="$TRAVIS_BRANCH.${TRAVIS_COMMIT::8}"
    - secure: "gE0OHyr/xVCtQtVA88erUZs+UjfAeixvWaxppmLx7ES8fBFZFao+BZm8lchrvOapY1n35ELxP1Een3MhIUaY8sk8TjPtWEDaelfWYuJayB25j/f0WIMMt6L5Rv2t07aHw55JcMHaZdmzWi+79vy+3DvLo5irSRpYeNYXR1BfvtJYYHur/GjgpptSBUF87m/R+kG7QzDRS7hq1CzfCQSdrSyztDUMPqpEuctusuGakPXmeSCJQBHmRM77zQ99IbPc83H75Eh0wkAb5vUtMoSrU5DeeVqfoYczaGHDl3qTxMeIK68lrwGvq4mzYjPSt4VGIMtoEkMSXSbpsmXu1I9w0Qmoz7sN9SXButhHAWirga6kjkUjQEJJ23r3bjDZBb6eOH6KyJqvn0aqJYqjKBRM8sn+/f4TjIMk0XAGl47Gw7uzs6v4mjS/+6jtuIlBEBy3nEcRIQ3LSTM2ncqGkpyTsO4QFC6BwOqP0UAHfIq2eiK0jIBTKRao7DJ3x3iMfIWptOoGolw1nE3xwRTa9OhtB5MyAGDCX0mQG2GZ3sr2/banOGxX7luWU7zRxdOLpkUmbCYEyNjrX0C5MTwbtI0yAEkFBtgrjzPMTmVWpS/oGvwKhHKUz/aUgkmmZ4Q1XGPNGikniu//azC6EuiSZBzIu2/OifjFNxytd9TLX4+MheY="
    - secure: "cpZSk/nywLaqJNDvuLuz/O9bcnsDo7j+b5tcJ/fKhH5hlImOTXjLIdm3MUuz4n58of76mfO3SYaTxblrM4k85derLtPyt7xBZ/MrQsefsq7NeQpJ4jOdhRMYGzAZyoUg7Bf3SWv5MKcCs0qS1wQxh5zJsG65td6FSr3AyKh2nmndP3WYDP+5wTdx3vOAog8MCfH71LgQu7XfG8eOwzNEEDGYTL9JNKLrSPLrBcLolrXkh+YoIWuXwauEIJpJ2WCJ2HJeypKHptT7KxVBDXHYQzw9oqSds8NuUjuVsNuBcXevN6MFoha4BDb+Nc5dfix4+BY39WtLXYtayjXeUbEyeezK5QfQHDA54/jknxmCm9FpuXnafnmGXH3PZl+SzOPTMhLIfXITKN5mrqR6ef3RcFOfxk2XGS/kTEBmExRwwywzXFIrcmBmkDJEELIjPqqm3BuxrVmd3gANbSrbMbbGoyBh8pgYcKN0hmhGPgahE2FOi33fr8SfqWpNW91pnAN3jE74BmZlp4Xh8XtP28UltRAbTbO64oz+1g5eLpwLk+i9y+QRxW695YhItNVlOpFjOVZNVSnwKlGaM3qzvDH5MS5SxunQzUXGw2h4nFHiczVWgzXr8eBgL+Z9UJg5m8HkENJUPTauAOg9M6F7vipevqQqlodrOgZsuGwz0yDpYrI="
    - secure: "Qv8gndv4lmpMmZH43trqFgzSSV1YTTrUOZrzEeFBbwdoA8lmv7Drj5hYL1kBDxUzmn1IsTHbDTWK/mK4NzXIz7womxCXiFVj4NJsbVDelagQfVhWn2ZM3CxsITwsuumbdOpDjlW5HaQiGJfSV7wmc3/Vy8nQrOKXR3gciNqT9+a439KeLeqXjCrBp+DqBvziiXhtovFE37hqzQKn0Np7NMOZy0oxg/2nev/dOLKB65slp/zF1mocw/mCpZhtWCQh3yJg7STPWa3JppgbTLmzkZwXLohfxpekyEx474k+6XM4gEi6/4Vv4UDxx21kDXtDwr01ekC03AHLVPa/od0YxZCzCygrVWVsXmPVPCx1qD/AsaHbuLNf3u09H/dHwt/7HZmFGge4DtsTEl0gmsoL5yUi/g5nKOAE6e3znMfgAPFc8y2YJ0cRpzdAZYwBTX2u2ev6JLLIzZKC5rSfFx06KfcgkkkO4ygCelgkKHEjzNEpw7ntwi9N72zpWD6kdsOSTwVzLni98JpZRaxb1TfRPeyx88uR//CA1vp0VRd9EOc6Yl5F1WMXM6b1OCinIN/ITIzcRvhvUcj1c6Hfa5F4BsiQyKV372od5A/8qlfB6NbDG4Hol5V3VcIzQe02vKRyYFOQW9ATnA7c9Nch5UpbD1cChpD/knnQ6IqlVfEPchs="
    - secure: "t1VyXy1M6CYgGBSxu9ioJf6EjDhTh80fLuqquGAgzb6snRpNa3rFGbnBj3BjKTwjXFfYAGOVKyIlj6DzWCFiWx8DabdYRLJhiWYjtcXu6LriYjIpupZw0fCQGcDcx/NN68tcgTQFNrG3CSimBZDX0o86Dy+SSbLLOse9mqfEV61nb4nErtKZTfJzBauBvbv3L19abjUtUGY4/xc6FpZ7lau6DwhaEy4Dt5vPSwngQ4UBYfINnIGaFH/PFTyoumZLlSGkPsTitEOPdI5A6abVfDuZrTBv5FVEKjNxJqb1qaZO+vy1Ka58PU1LRwJnAjKE51HPPXDum0A9niXmt8LtFlv6HmHKXfMyIzsTTIJOy6NmB4v5sgsjXbxPKC56ntZOAzeAteJSa+aD9G/Jp5EKCWUGa6s+g9WvG/zx3fIk3ilOzlNu6DlLIjPvhotelKfiltPRONYPXTL3aVyt0rHZzj0ZUOcZHG1pA9z0tpbxdzxd+VC/laliPq7xf2/QHzRnB55MS9S28XURLugLduBAiGWSwNPz4QYTf+1SDCnO3aDJWQDkxAw5JVJOcduIW05lC+MG5f2XNVgqO+wTMYNEBfE79Ge0giGIW9L5bv0lK21Ntqw2eK8Rza5EgkUGE5k21sVAEBFFBBcWPNZ/XkBFgd3ohnGJtj0izwmt0uwrW3U="
    - secure: "ctuFbt0rC8aldc63bVUfi5ZsZzU+I/5ko8FtxzxIACIm/b/xHZf/rvcWA3Wdm5glnB8zbfq1VU/ymITXatNhSThd8hTjsdneF+l/KBQjGPZRpODMeGpoL+fL9Hf485i+v0NGMz0Wh+cagA5FU2CeGJ0wUHdyUFwy33sRMv7zGgJybppg3WArGTCPniY9fXWdnFmTfc9Rx+nRtJiGkB9Wej+8XSbHS6u+Z9GalRLuFd5WJ0lPzCIq7gbp9hfsWqG9YRWwmp7lQ3COg6TkgQGwUDeeW575tPFxJsgaW3eFa0adgBtGvmvSODAMjkhXpS9cUDrdj/n9MdgrNAObd+AAsRrKC+F376OgQhT0lDAT5TYF3AcZT6RUW8YaIk5O7kOzKq/3b+dVJbsg9OQ1LsGlBtbbZ1FufRY3W3UeHHPREagzP6pnATUpkl4UzhYomOBziYDkgTSPHQmmKdGlD/hthdCC7JmEMtlu+9ojdBhr5tcpxzD2uQBWIUe9dgiLvlECK37mCBuy6dN1rcA8CmbQae4kUXwX15Yr1U7Jy37Z1cV8IFd0ADhSV6feWCm/FlxxHX9iEifPaprtezKXEz9BDdrl3XRSml8HpbN6ecQ7Sc89/MXr8EMphGLZSVEAXCbLQbRiqjSQSVhis7kpSOFKcMXASkiBMb9vl+m0hz+oNLo="

install:
  - docker build -t $IMAGE_NAME:$IMAGE_TAG .

before_script:
  - docker run -d --name=database postgres

script:
  - docker run --rm -e DB_HOST=database -e MIX_ENV=test --link=database $IMAGE_NAME:$IMAGE_TAG bash -c "./wait_for_services.sh && mix test 1>&1"

after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - "[ \"${TRAVIS_PULL_REQUEST}\" = \"false\" ] && docker push $IMAGE_NAME:$IMAGE_TAG || false"

before_deploy:
  - export KUBECTL="docker run --rm -v `pwd`:/app lachlanevenson/k8s-kubectl:v1.2.4 --server=$KUBERNETES_HOST --certificate-authority=/app/ca.pem --token=$K8S_TOKEN"
  - sed -i.bak "s#$IMAGE_NAME:latest#$IMAGE_NAME:$IMAGE_TAG#" haypoll-deployment.yml
  - sed -i.bak "s#$IMAGE_NAME:latest#$IMAGE_NAME:$IMAGE_TAG#" haypoll-migration.yml
  - $KUBECTL create -f /app/haypoll-migration.yml --namespace=haypoll
  - export POD=$($KUBECTL get pods --selector=app=haypoll-migration --namespace=haypoll --output=jsonpath={.items..metadata.name})
  - $KUBECTL attach $POD --namespace=haypoll || true
  - $KUBECTL delete -f /app/haypoll-migration.yml --namespace=haypoll

deploy:
  provider: script
  skip_cleanup: true
  script: $KUBECTL apply -f /app/haypoll-deployment.yml --namespace=haypoll
  on:
    branch: master
