apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    app: postgres
    role: master
    tier: backend
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres
    role: master
    tier: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres-master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: postgres
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
        env:
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
        volumeMounts:
          - name: volume-azure-bddata
            mountPath: /var/lib/postgresql/data
      volumes:
      - name: volume-azure-bddata
        azureDisk:
          diskName: KubeAzureBDData
          diskURI: https://vmsystemdisks.blob.microsoft.net/vhds/bd.vhd
