apiVersion: v1
kind: Service
metadata:
  name: haypoll
  labels:
    app: haypoll
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: haypoll
    tier: frontend
