apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    app: postgres
    role: master
    tier: backend
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres
    role: master
    tier: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres-master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: postgres
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: haypoll
  labels:
    app: haypoll
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 31001
  selector:
    app: haypoll
    tier: frontend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: haypoll
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: haypoll
        tier: frontend
    spec:
      containers:
      - name: haypoll
        image: edevil/haypoll:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
          - name: DB_HOST
            value: database
          - name: DB_PASS
            value: postgres
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
            httpHeaders:
              - name: X-Custom-Header
                value: Awesome
          initialDelaySeconds: 15
          timeoutSeconds: 1