apiVersion: v1
kind: Service
metadata:
  name: haypoll
  labels:
    app: haypoll
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 31001
  selector:
    app: haypoll
    tier: frontend
